import assert from "node:assert/strict";
import { loadRazorpayCheckout } from "../utils/razorpay.js";
const scripts = [];
globalThis.window = {};
globalThis.document = { createElement() { return { remove() { this.removed = true; } }; }, head: { appendChild(script) { scripts.push(script); } } };
const first = loadRazorpayCheckout();
assert.equal(loadRazorpayCheckout(), first, "COD and Online share one pending loader");
assert.equal(scripts.length, 1);
scripts[0].onerror();
await assert.rejects(first, /could not be loaded/);
assert.equal(scripts[0].removed, true);
const retry = loadRazorpayCheckout();
assert.equal(scripts.length, 2);
window.Razorpay = class Razorpay {};
scripts[1].onload();
assert.equal(await retry, window.Razorpay);
assert.equal(await loadRazorpayCheckout(), window.Razorpay);
assert.equal(scripts.length, 2, "loaded global constructor is reused without another script");
console.log("Shared Razorpay loader deduplication, failure cleanup and retry assertions passed.");
